platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'YTKNetworkDemo' do
    pod 'YTKNetwork', :path => '../'
    pod 'AFNetworking', '~> 4.0.0'
end

target 'YTKNetworkDemoTests' do
    pod 'YTKNetwork', :path => '../'
end

